<script setup>
import { computed, onMounted, ref } from 'vue'
import { api } from '../api'
const metals=ref([]);const loading=ref(true);const error=ref('')
const invested=computed(()=>metals.value.reduce((sum,m)=>sum+m.bought_price,0));const value=computed(()=>metals.value.reduce((sum,m)=>sum+m.buyback_price,0));const gain=computed(()=>value.value-invested.value)
const money=value=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value)
onMounted(async()=>{try{metals.value=await api('/metals')}catch(e){error.value=e.message}finally{loading.value=false}})
</script>
<template><div class="page"><div class="page-heading"><div><p class="eyebrow">Portfolio</p><h1>Precious metals</h1><p class="muted">A clear view of every piece you hold.</p></div><RouterLink to="/metals/new" class="button primary">+ Add metal</RouterLink></div><section class="summary-grid"><article><span>Invested</span><strong>{{ money(invested) }}</strong></article><article><span>Buyback value</span><strong>{{ money(value) }}</strong></article><article><span>Unrealized return</span><strong :class="gain>=0?'positive':'negative'">{{ money(gain) }}</strong></article></section><p v-if="error" class="alert">{{ error }}</p><div v-if="loading" class="empty">Loading your ledger...</div><div v-else-if="!metals.length" class="empty"><div class="empty-mark">A</div><h2>Your ledger is ready</h2><p>Add your first precious metal to begin tracking its value.</p><RouterLink to="/metals/new" class="button primary">Add first metal</RouterLink></div><section v-else class="metal-list"><RouterLink v-for="metal in metals" :key="metal.id" :to="`/metals/${metal.id}`" class="metal-row"><div class="metal-icon">{{ metal.type.slice(0,2).toUpperCase() }}</div><div><strong>{{ metal.type }}</strong><span>{{ metal.brand }} · {{ metal.weight }} g</span></div><div class="metal-value"><strong>{{ money(metal.buyback_price) }}</strong><span>Buyback value</span></div><span class="arrow">›</span></RouterLink></section></div></template>
